name: Send Message to Google Chat

on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  google-chat-action:
    name: Google Chat GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: Notify Google Chat
        if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          jobStatus: ${{ job.status }}
          title: 測試repo更新
          subtitle: ${{ github.event.pull_request.title }}
          additionalSections: '[{"header":"更新內容","collapsible":true,"widgets": [{"decoratedText": {"startIcon": {"knownIcon": "DESCRIPTION"},"text": "${{ github.event.pull_request.body }}"}}]}]'